# Generated by Django 3.2.6 on 2021-11-20 19:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeScan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('resume', models.JSONField(blank=True, null=True)),
                ('job', models.TextField(blank=True, null=True)),
                ('expected_score', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('outputs', models.JSONField(blank=True, null=True)),
                ('ip', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
